src/lib/DynamicContent.mocks.ts
src/lib/model/ContentItem.ts
src/lib/model/ContentRepository.spec.ts
src/lib/model/ContentRepository.ts

Basic list content items implementation with e2e coverage

List content items

---

package-lock.json
src/lib/DynamicContent.mocks.ts
src/lib/DynamicContent.ts
src/lib/model/ContentRepository.spec.ts
src/lib/model/ContentRepository.ts
src/lib/model/Folder.spec.ts
src/lib/model/Folder.ts

Wire up folder list and creation endpoints.

Feature: manage folders

---

src/lib/DynamicContent.mocks.ts
src/lib/hal/models/HalResource.spec.ts
src/lib/hal/models/HalResource.ts
src/lib/hal/services/HalClient.ts
src/lib/hal/utils/HalMock.ts
src/lib/model/ContentItem.spec.ts
src/lib/model/ContentItem.ts

- Ability to update a content item
- Coverage for update content item
- Minor refactor of HalResource to remove duplicate code

Feature: Update content item

---

package-lock.json
package.json

fixed code coverage (missing sourceMap config prop)

chore(nyc): bump to 14.1.1 (security alert on nyc dep set-value)

---

.github/workflows/nodejs.yaml
.travis.yml

Re-used the github actions from the dc-cli app
Updated travis to test against nodejs 8, 10 & 12.

ci(github actions): build & test the sdk

---

src/lib/DynamicContent.mocks.ts
src/lib/model/SearchIndex.spec.ts
src/lib/model/SearchIndex.ts
src/lib/model/SearchIndexTopHits.ts

NA
- Exposes the "top-hits" API
Awaiting for the API to be released/deployed.

feat(search index): exposed top hits api

---

src/index.ts
src/lib/DynamicContent.mocks.ts
src/lib/model/SearchIndex.spec.ts
src/lib/model/SearchIndex.ts
src/lib/model/SearchIndexSearchesWithNoResults.ts
src/lib/model/SearchIndexTopFiltersNoResultSearch.ts

NA
- added top-filters-no-result-search api call

feat(search indexes): added top-filters-no-result-search api call

---

src/index.ts
src/lib/DynamicContent.mocks.ts
src/lib/model/SearchIndex.spec.ts
src/lib/model/SearchIndex.ts
src/lib/model/SearchIndexSearchesCount.ts

NA
- Exposed the Search Indexes "searches-count" API
(includes #54 )

feat(search indexes): added searches-count api

---

src/index.ts
src/lib/DynamicContent.mocks.ts
src/lib/model/SearchIndex.spec.ts
src/lib/model/SearchIndex.ts
src/lib/model/SearchIndexNoResultsRate.ts

Added support for new search index analytics/no-results-rate endpoint

feat(search index analytics): added a new endpoint for no results rate

---

src/lib/model/Edition.ts
src/lib/model/FindByDate.ts
src/lib/model/Hub.ts

Unable to find an edition by a date range
- Able to find an edition by date range

feat: expose edition find by date

---

src/lib/DynamicContent.mocks.ts
src/lib/model/ContentRepository.spec.ts
src/lib/model/ContentRepository.ts
src/lib/model/ContentTypeSchema.spec.ts
src/lib/model/ContentTypeSchema.ts
src/lib/model/Event.spec.ts
src/lib/model/Event.ts
src/lib/model/SearchIndex.spec.ts
src/lib/model/SearchIndex.ts
src/lib/model/Snapshot.spec.ts
src/lib/model/Snapshot.ts
src/lib/model/Webhook.spec.ts
src/lib/model/Webhook.ts

If you only had a content item id, there's no way to walk up the tree back to a hub via the content items repository. 
- exposed a hub() all of the resources that have a hub HAL link

feat: added hub() methods to the resource that have hub hal links

---

src/lib/DynamicContent.mocks.ts
src/lib/hal/utils/HalMock.ts
src/lib/model/Hub.spec.ts
src/lib/model/Hub.ts

Can't use the SDK to find "slots" Content Repositories
- Added the [Content Repository findByFeature()](https://amplience.com/docs/api/dynamic-content/management/index.html#operation/findContentRepositoryWithFeature) support

feat(content repository): find by feature

---

README.md
src/lib/model/ContentItem.ts
src/lib/model/ContentRepository.ts
src/lib/model/ContentType.ts
src/lib/model/ContentTypeCachedSchema.ts
src/lib/model/Edition.ts
src/lib/model/EditionSlot.ts
src/lib/model/Event.ts
src/lib/model/Hub.ts
src/lib/model/Snapshot.ts
src/lib/model/Webhook.ts

Incorrect api docs link
- updated to use the new api docs

docs: updated api docs links

---

package.json
src/index.ts
src/lib/DynamicContent.mocks.ts
src/lib/model/ContentItem.ts
src/lib/model/Facets.ts
src/lib/model/Hub.spec.ts
src/lib/model/Hub.ts

feat(content items): facets support

---

src/lib/utils/WebhookSignature.ts

When using snowpack to build a browser app it cannot import crypto 
- dynamically import crypto lib

feat(webhook signature): dynamically import crypto lib

---

.github/workflows/nodejs.yaml

previously the github actions would include the nodejs version.
- version has been removed from the github action name

chore: github actions name

---

src/index.ts
src/lib/DynamicContent.mocks.ts
src/lib/DynamicContent.spec.ts
src/lib/DynamicContent.ts
src/lib/hal/models/HalResource.ts
src/lib/hal/services/HalClient.ts
src/lib/model/ContentItem.spec.ts
src/lib/model/ContentItem.ts
src/lib/model/Hub.ts
src/lib/model/WorkflowState.spec.ts
src/lib/model/WorkflowState.ts

Missing workflow states
- get, list & update workflow states
- assign workflow states to a content item

feat(workflow-state): assign to content-item and update workflow-state support

---

src/lib/DynamicContent.mocks.ts
src/lib/model/ContentItem.spec.ts
src/lib/model/ContentItem.ts

Could not remove workflow state from an item.
Can remove workflow state assignment from an item.
-
-
-

feat: unassign workflow state from an item

---

.github/workflows/app.yaml
.github/workflows/release.yml

Using old/deprecated GitHub Actions
- Updated GitHub Actions to their latest version

fix(gh actions): nodejs deprecation warnings

---

README.md

Update readme to include a link to the developer hub that has details on how to create and manage PATs
-
-
-

docs: update readme pat

---

package-lock.json
src/lib/DynamicContent.mocks.ts
src/lib/hal/models/HalResource.ts
src/lib/http/AxiosHttpClient.spec.ts
src/lib/model/ContentItem.spec.ts
src/lib/model/ContentItem.ts
src/lib/model/ContentRepository.spec.ts
src/lib/model/ContentRepository.ts
src/lib/model/ContentType.spec.ts
src/lib/model/Extension.spec.ts
src/lib/model/HierarchyChildren.ts
src/lib/model/HierarchyParents.ts
src/lib/model/LocalizationJob.spec.ts
src/lib/model/Page.ts
src/lib/model/SearchIndexSearchesWithNoResults.ts
src/lib/model/SearchIndexTopFiltersNoResultSearch.ts
src/lib/model/SearchIndexTopHits.ts
src/lib/model/SearchIndexTopSearches.ts
src/lib/model/Settings.ts
src/lib/oauth2/services/Oauth2AuthHeaderProvider.ts

Repo -> content item -> create and content item -> update don't support params
The two methods above now support optional params (currently just 'ignoreSchemaValidation')

feat: add 'ignore validation' support

---

README.md

- Copyright date outdated
- Copyright date corrected

fix: copyright version
