README.md

With the addition of const and let you're unable to reassign a const you are however allowed to change the properties
for example
const event = {}
event.id = '123'
but you can't then do
event = {} 
as it will throw the error
// TypeError: invalid assignment to const event

fix(README) changed const to let as would throw error for trying to reassign a constant

---

src/lib/model/Hub.ts

Sort is currently not supported on the content-type-schema list endpoint

fix(content-type-schema): removed the sort support from the sdk

---

package-lock.json
package.json

Previously ava was running against the compiled code and nyc (for certain poeple) was using the compiled js and not the source map that was generated from the tsc.
The coverage report is lower than it was previously, as now the tests are testing files that previously weren't being tested, src/lib/oauth2/* is a example of this as the test runner uses it's own fake client to mock calls.

build(coverage): updated ava to use ts-node and update nyc config

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Add issue and pr templates that are used in the dc-delivery-sdk-js (tweaked to refer to dc-management-sdk-js)

chore: github pr & issue templates

---

src/lib/DynamicContent.mocks.ts
src/lib/model/ContentItem.spec.ts
src/lib/model/ContentItem.ts
src/lib/model/ContentType.spec.ts
src/lib/model/ContentType.ts
src/lib/model/ContentTypeSchema.spec.ts
src/lib/model/ContentTypeSchema.ts

Rather simple - allows access to content's archive and unarchive links via their `.related` object. This PR adds this functionality to three different resource types:
- Content Type Schemas
- Content Types
- Content Items
There are tests for each to ensure that the correct link is called. From what me and QA have tested, all of these appear to be working properly. Attempting to archive content that is already archived (and vice versa for unarchiving) will throw a hal link permissions error. For some reason, Content Items just fail silently, but this seems to be intentional.

Add support for archive and unarchive hal links for Content

---

src/lib/model/Folder.ts

While working with the folders api, I noticed I wasn't able to pass in any pagination options for listing subfolders or subitems, meaning that it just showed the first 20 items every time (could never see the ones past that point). This change allows pagination and sort options to be passed to the requests.

Folders: add proper pagination support to subfolder and subitem list

---

src/lib/DynamicContent.mocks.ts
src/lib/hal/models/HalResource.spec.ts
src/lib/hal/services/CURIEs.ts
src/lib/hal/services/HalClient.spec.ts
src/lib/http/AxiosHttpClient.spec.ts
src/lib/oauth2/services/OAuth2Client.spec.ts

Module bundlers such as Rollup.js are unable to bundle the SDK (out the box) as the combination of import and require module syntax confuses the bundler (as the bundler determines which module system is being used). In cases where a project bundles the SDK for browser environments the require is not converted to be browser friendly, resulting in errors.
The SDK has been update to only use `import` in all instances.

refactor(curie): using import instead of require to avoid module bundler issues

---

package.json

Using this repo as a npm git dependency fails as npm checks out the project and applies the '.npmignore' rule set --  ignores all .ts files and only includes .js files, which there are none.
Meaning your dependant application will fail.
Adding  "npm ci && npm run build" in the prepack phase builds the lib before npm runs it local 'pack' command when using this repo as a git dependency.
This change has been tested and verify using an external app running on Netlify, contact me directly for the example URL.

build(npm): added a prepare phase to build the app

---

src/index.ts
src/lib/model/SearchIndexStatistics.ts

All SearchIndex related classes aren't exported
- exports the search indexes related classes and enums

feat: exporting search indexes classes and enums

---

package.json
src/lib/DynamicContent.mocks.ts
src/lib/model/SearchIndex.spec.ts
src/lib/model/SearchIndex.ts

No includeReplicas support
`npm run cov` fails to open coverage report
- Added the `includeReplicas` param to the top-hits search indexes api
- fixed `npm run cov`
- improved code coverage

feat(search indexes): include replicas option

---

src/lib/model/Hub.ts

`parentId` and `projection` are missing from the supplied parameters when calling the list indexes endpoint
The aforementioned parameters have been included in the list indexes request.
Pointed at the search analytics branch to show current changes only

fix(search indexes): adds all supplied parameters to a list request

---

src/index.ts
src/lib/DynamicContent.mocks.ts
src/lib/model/SearchIndex.spec.ts
src/lib/model/SearchIndex.ts
src/lib/model/SearchIndexUsersCount.ts

N/A
- adding index search analytics users-count api call

feat(search indexes): adding users-count api call

---

src/lib/DynamicContent.mocks.ts
src/lib/model/Hub.spec.ts
src/lib/model/Hub.ts

Unable to get Content Type by ID
Added support to get Content Types by ID

feat(content types): get content type by id

---

src/lib/DynamicContent.mocks.ts
src/lib/DynamicContent.ts
src/lib/model/ContentType.spec.ts
src/lib/oauth2/services/OAuth2Client.spec.ts
src/lib/oauth2/services/OAuth2Client.ts

- `authUrl` points to `auth.adis.ws`
- card icons point to `http://apps.dev-artifacts.adis.ws',
- `authUrl` now points to `auth.amplience.net`
- card icons now point to `bigcontent.io'

feat: updating auth and icon urls

---

src/lib/DynamicContent.mocks.ts
src/lib/model/Webhook.spec.ts
src/lib/model/Webhook.ts

Here I added a number of additional properties to the `Webhook` model.
I don't believe I have visibility into all of the potential `Webhook` filter `type`s, the only value I've seen in the interface is `in` and `equal`.
Similarly, I'm not sure if there are other `customPayload` types other than `text/x-handlebars-template`.
(**Note: There are a number of warnings, 44 I believe, but I don't believe this PR adds any**)
Currently unable to specify Webhook models `method`, `headers`, `customPayload`, or `filters`.
- All of the above properties now exist on the typescript definition / class
- These work / are testing with the current API and allow these values to be set in the …

feat(webhooks): add webhook properties for headers, method, filters and customPayload

---

src/lib/model/ContentItem.spec.ts
src/lib/model/ContentItem.ts

Locale is not present on the ContentItem type, but it is regularly undefined when returned by DC.
The type definition now allows `locale` to be undefin
This may cause typescript compilers to require a null check. I'm not sure if this counts as a breaking change, feel free to comment if it is.
Needed for `fix/locale` over in `dc-cli`

fix(content items): make locale nullable

---

src/lib/DynamicContent.mocks.ts
src/lib/model/ContentType.spec.ts
src/lib/model/ContentType.ts
src/lib/model/ContentTypeSchema.spec.ts
src/lib/model/ContentTypeSchema.ts
src/lib/model/Status.ts

The `Status` enum is not present on Content Types, and Content Type Schemas. It's also missing the `ARCHIVED` status, used by many of the existing types using this enum such as content items.
The `status` property has been added to content types and schemas. The `ARCHIVED` status has been added to the enum.

feat: include archived in status enum, add it to content type and schema

---

src/lib/DynamicContent.mocks.ts
src/lib/model/AssignedContentType.spec.ts
src/lib/model/AssignedContentType.ts

There is no way to get the webhooks attached to assigned content types in search indexes.
The user can now request the webhook, activeContentWebhook and archivedContentWebhook from an assigned content type. This is useful for discovering and updating webhooks used by search indexes.
This is used by the search indexes PR over in dc-cli.

feat: implement fetching webhooks for search index assigned content types

---

src/lib/DynamicContent.mocks.ts
src/lib/model/ContentItem.spec.ts
src/lib/model/ContentItem.ts
src/lib/model/LocalizationJob.spec.ts
src/lib/model/LocalizationJob.ts

Management SDK is missing a method to get localizations for ContentItem.
Added method to get localizations for ContentItem.

feat: add method to get localizations for ContentItem

---

src/lib/hal/models/HalResource.ts
src/lib/model/Edition.ts

Requesting an edition's slots does not pass any pagination parameters, so you always get back page 0 with size 20. This makes it impossible to list more than 20 slots.
Listing slots now passes pagination parameters to the API.
- Params object is now passed when calling the `list-slots` HAL link.
- The `list-slots` HAL link from the API is automatically rewritten to include pagination parameters, so they are not ignored. This os a bug with the API.
There's no planned fix for the HAL link bug for a while, hence the weird workaround.

fix: pass pagination parameters to edition list-slots link

---

src/lib/DynamicContent.mocks.ts
src/lib/model/Hub.spec.ts
src/lib/model/Hub.ts
src/lib/model/StatusFilterable.ts

Listing content-types was missing `status` parameter.
Introduced optional `status` parameter for content-type listing.
N/A

fix: content type list supports status parameter

---

.github/workflows/release.yml

Builds not being ran on release-please
Use a service user to run the release-please, to trigger the builds

fix(gha release): run build on release-please

---

package-lock.json
package.json

- Docs do not build due to Typescript incompatibility
- Doc now build
-
-

fix: updating typedoc to version that supports typescript 5.8
